//import 'package:flutter/material.dart';

import 'package:product_test/model/product.dart';

class Products {
  //const Products();

  //Widget build(BuildContext context) {
  static List<Product> products = [
    Product(
        id: 1,
        name: 'Shirt',
        briefDescription: 'Lime',
        description: 'Shirt description',
        color: 'Blue',
        size: 'L',
        price: 10,
        currency: '\$',
        like: false,
        picture: 'assets/product/1.jpg'),
    Product(
        id: 2,
        name: 'Longsleeve Violeta',
        briefDescription: 'Mango',
        description: 'Longsleeve Violeta description',
        color: 'Orange',
        size: 'S',
        price: 46,
        currency: '\$',
        like: false,
        picture: 'assets/product/2.jpg'),
    Product(
        id: 3,
        name: 'T-Shirt',
        briefDescription: '&Berries',
        description: 'T-Shirt description',
        color: 'Black',
        size: 'S',
        price: 39,
        currency: '\$',
        like: false,
        picture: 'assets/product/3.jpg'),
    Product(
        id: 4,
        name: 'T-Shirt Sailing',
        briefDescription: 'Mango Boy',
        description: 'T-Shirt Sailing description',
        color: 'White',
        size: 'M',
        price: 10,
        currency: '\$',
        like: false,
        picture: 'assets/product/4.jpg'),
    Product(
        id: 5,
        name: 'Evening Dress',
        briefDescription: 'Dorothy Perkins',
        description: 'Evening Dress description',
        color: 'Purple',
        size: 'S',
        price: 12,
        currency: '\$',
        like: false,
        picture: 'assets/product/5.jpg'),
    Product(
        id: 6,
        name: 'Shirt',
        briefDescription: 'Lime',
        description: 'Shirt description',
        color: 'Blue',
        size: 'L',
        price: 10,
        currency: '\$',
        like: false,
        picture: 'assets/product/1.jpg'),
    Product(
        id: 7,
        name: 'Longsleeve Violeta',
        briefDescription: 'Mango',
        description: 'Longsleeve Violeta description',
        color: 'Orange',
        size: 'S',
        price: 46,
        currency: '\$',
        like: false,
        picture: 'assets/product/2.jpg'),
    Product(
        id: 8,
        name: 'T-Shirt',
        briefDescription: '&Berries',
        description: 'T-Shirt description',
        color: 'Black',
        size: 'S',
        price: 39,
        currency: '\$',
        like: false,
        picture: 'assets/product/3.jpg'),
    Product(
        id: 9,
        name: 'T-Shirt Sailing',
        briefDescription: 'Mango Boy',
        description: 'T-Shirt Sailing description',
        color: 'White',
        size: 'M',
        price: 10,
        currency: '\$',
        like: false,
        picture: 'assets/product/4.jpg'),
    Product(
        id: 10,
        name: 'Evening Dress',
        briefDescription: 'Dorothy Perkins',
        description: 'Evening Dress description',
        color: 'Purple',
        size: 'S',
        price: 12,
        currency: '\$',
        like: false,
        picture: 'assets/product/5.jpg'),
  ];
  //}
}
